name: we_skia_custom_font
description: we_skia_custom_font.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Segoe_form_assets
      fonts:
        - asset: assets/Segoe_UI.ttf

    - family: Alata_Regular_form_assets
      fonts:
        - asset: assets/Alata_Regular.ttf

    - family: FiraCode_form_assets
      fonts:
        - asset: assets/FiraCode_Medium.ttf
